schema: "classroom50/repo-config/v1"
classroom: "cprog"
assignment: "02-conveyor-belt"
owner:
  username: "FrederikSeerupDTU"
  id: 323662213
  accepted_at: "2026-09-10T19:35:39Z"
source:
  owner: "dtucprog"
  owner_id: 316954301
  repo: "02-conveyor-belt"
  branch: "main"
